export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_ALL_DIETS = "GET_ALL_DIETS";
export const GET_RECIPE = "GET_RECIPE";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const SET_RECIPES = "SET_RECIPES";
export const SORT_RECIPES = "SORT_RECIPES";
export const FILTER_RECIPES = "FILTER_RECIPES";
export const SEARCH_RECIPES = "SEARCH_RECIPES";
